### ISSUE TITLE
CrashPlan and Box not working after Lib transfer

### ISSUE THREAD

**Issue by bradleyramos** [WITwercode/scripts#20]
User accounts set up using simple_setup cannot open box and CrashPlan. Resolved after transferred Library folder is deleted. But why?

**Comment by WuZJohn** [comment]
Library folder deleted as workaround is not transferred from source, instead is the one generated by MacOS on first boot.

**Comment by WuZJohn** [comment]
Deleting the following folder seems to do the trick, but note that it is a user's library folder, not the Systems, so there doesn't seem to be new_user.sh that is at fault here (doesn't create any files). 

"/Users/YOURUSERNAMEHERE/Library/Application Support/CrashPlan"

**Comment by WuZJohn** [comment]
Issue not occurring with DEP
