### ISSUE TITLE
GUI Application Issues

### ISSUE THREAD

**Issue by bradleyramos** [WITwercode/scripts#26]
- can't run twice (reset "command" at the end of the run?)
- can't enable filevault
- folder picker opens up when deselecting (after you just picked a folder..)
- no spaces are allowed in the last name of a user
- script paths are hardcoded (must be in /Users/admin/Downloads/scripts-master)
- triggering an error in transfer.sh will crash everything and may warrant a restart of machine

**Comment by WITwercode** [comment]
Also doesn't work if source has a space

**Comment by bradleyramos** [comment]
Spaces handled by #27

**Comment by bradleyramos** [comment]
Can't run twice handled by or before #30 
Folder picker was handled by a commit directly to master

**Comment by WITwercode** [comment]
Remains to be done:
Can't enable filevault
Errors in scripts hang gui

**Comment by WuZJohn** [comment]
Agree with @WITwercode

**Comment by WuZJohn** [comment]
Opening new issue for filevault
