### ISSUE TITLE
Must not download from terminal

### ISSUE THREAD

**Issue by bradleyramos** [WITwercode/scripts#36]
For some reason code doesn't work when you download it from github
The same code will work if you copy it using the scp terminal command
Possibly has to do with the zip/unzip of the file

**Comment by WuZJohn** [comment]
App bundle (in fact, all files, but bash scripts don't care) are quarantined on download from web by MacOS. Can be solved by `xattr -r -c [scripts folder]` to clear flags, but no real point since could just download non-quarantined files from witmac.

**Comment by WuZJohn** [comment]
Needs dev account to sign app bundle.

**Comment by WuZJohn** [comment]
Turns out real issue is that script location was hardcoded in both bash scripts and swift code
