### ISSUE TITLE
Filevault no longer prompts to allow user from Sys Pref after WitUp

### ISSUE THREAD

**Issue by WuZJohn** [WITwercode/scripts#41]
Upon creation of a new user by WITup GUI, Sys Pref used to list that that the user was not enabled through filevault in Sys Pref -> security. It no longer does so, and the following command must be run from terminal to enable FileVault. `sudo fdesetup -usertoadd USERNAME_HERE`

Oddly, the user's credentials allow the user to add himself to Filevault (previously, the admin credentials were needed since the user's credentials are not in filevault before adding).

**Comment by WuZJohn** [comment]
https://www.jamf.com/jamf-nation/discussions/12143/filevault-user-add-script-help#responseChild70465
Possible solution. Expects and send potentially allows sending input to fdesetup

**Comment by WuZJohn** [comment]
A different method that works for other bash scripts that need input is `printf "Input1/nInput2/n" | two_input_script.sh`. Unfortunately, does not work for fdesetup. Presumably for security reasons.

**Comment by bradleyramos** [comment]
Actually, the command you want to run will be sudo `sudo fdesetup add -usertoadd USERNAME_HERE`
However, this only works with the admin account credentials. And so, the search for a solution continues.
