### ISSUE TITLE
no_lib_transfer ignores e.g. Outlook Data files, some system preferences, etc.

### ISSUE THREAD

**Issue by WuZJohn** [WITwercode/scripts#7]
By design, no_lib_transfer takes only the Bookmarks from ~/Library since the rest can't be transferred by a simple `cp` command. A simple implementation using `tar` should at least produce an archive that can be used just in case these files are necessary.

**Comment by WuZJohn** [comment]
`tar -cf [tar_file.tar] [directory_to_archive]` is one possible implementation, but perhaps no verbose mode to avoid overloading the terminal.

**Comment by bradleyramos** [comment]
closed by #9

**Comment by bradleyramos** [comment]
closed by #9
